#debug: true
#trace: true

#logging:
#  level:
#    web: DEBUG
#    org:
#      example:
#        employee: INFO
#    software:
#      amazon:
#        awssdk: DEBUG
#    org:
#      springframework:
#        data:
#          redis: DEBUG
#    io:
#      lettuce: DEBUG

spring:
#  mvc:
#    servlet:
#      load-on-startup: 1
#
#  main:
#    banner-mode: on

  application:
    admin:
      enabled: false

  jmx:
    enabled: false
#
#  lifecycle:
#    timeout-per-shutdown-phase: 10s
  web:
    resources:
      add-mappings: false

  cache:
    type: redis
    cache-names: employee-directory-employees
    redis:
      cache-null-values: false
      enable-statistics: true
      use-key-prefix: false
#      time-to-live: 10m
#      host: aws-employee-directory-bxnhjl.serverless.use1.cache.amazonaws.com
#      port: 6379
  data:
    redis:
#      host: localhost
      host: aws-employee-directory-bxnhjl.serverless.use1.cache.amazonaws.com
      ssl:
        enabled: true

  output:
    ansi:
      enabled: NEVER

  threads:
    virtual:
      enabled: true

server:
#
#  port: 8080
#
  servlet:
    encoding:
      enabled: false
    multipart:
      enabled: false

  compression:
    enabled: false

  shutdown: graceful
#  max-http-header-size: 2KB
#
  tomcat:
#    connection-timeout: 5s
    mbeanregistry:
      enabled: false
    resource:
      allow-caching: false
#    remoteip:
#      remote-ip-header: x-forwarded-for
    accesslog:
      enabled: false
#
#error:
#  include-message: always

management:
  info:
    env:
      enabled: true
#    build:
#      enabled: true
    #    git:
    #      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    env:
      show-values: ALWAYS
    health:
      show-details: always

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
#    jmx:
#      exposure:
#        include: '*'

#api:
app:
  config:
    my-secret: abcdefgh
#    remote-cidr-filter: 127.0.0.1/32
