#debug: true

#logging:
#  level:
#    web: DEBUG
#    org:
#      example:
#        employee: INFO

#spring:
#  mvc:
#    servlet:
#      load-on-startup: 1
#
#  main:
#    banner-mode: off
#
#  application:
#    admin:
#      enabled: false
#
#  jmx:
#    enabled: false
#
#  lifecycle:
#    timeout-per-shutdown-phase: 10s
#  web:
#    resources:
#      add-mappings: false

#server:
#
#  port: 8080
#
#  servlet:
#    encoding:
#      enabled: false
#    multipart:
#      enabled: false
#
#  compression:
#    enabled: false
#
#  shutdown: graceful
#  max-http-header-size: 2KB
#
#  tomcat:
#    connection-timeout: 5s
#    mbeanregistry:
#      enabled: false
#    resource:
#      allow-caching: false
#    remoteip:
#      remote-ip-header: x-forwarded-for
#    accesslog:
#      enabled: false
#
#error:
#  include-message: always

#management:
#  info:
#    env:
#      enabled: true
#    build:
#      enabled: true
    #    git:
    #      enabled: true
#    java:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    jmx:
#      exposure:
#        include: '*'

#api:
#  config:
#    remote-cidr-filter: 127.0.0.1/32
